<?php
$sysdir = realpath(dirname(realpath(__FILE__)) . "/../") . '/';
require_once($sysdir . "includes/standalone-functions.inc.php");

$stalone_agencyCode = "lvdcerPr";  // Populated by the installer
$stalone_articleCount = 25; // The number of displayed articles

// If you'd like to ignore what channels you have selected in your agency profile and display releases from all channels, set this to true.
$stalone_showAllStories = false;

// Advanced options
$stalone_pageTitle = "SocialMac"; // title for release listing and XML feeds (default: "Latest %count% articles on prMac")
//$stalone_usePrettyUrls = false; // uncomment to force the use of short urls (should be autodetected by the script and thus unnecessary to set this)
$stalone_rssFilename = "feed.xml"; // Path to RSS feed (will be generated by the script; must exist and be writable by PHP; default: "feed.xml").
$stalone_tbTrackingPath = $sysdir . "tb_tracking"; // Path to the folder in which trackback data is stored (must exist and be writable by php; default: "system/tb_tracking")
$_prmac_cacheDir = $sysdir . "prmac_cache"; // Path to folder in which cached xml data is stored (must exist and be writable by php; default: "system/prmac_cache")
$stalone_baseURL = "{$_SERVER['PHP_SELF']}"; // URL from which prmac.php is accessed. (default: "{$_SERVER['PHP_SELF']}")
$stalone_generateProbability = 15; // increase to 100 if you have a very high-traffic site
$stalone_showSummaries = true; // whether or not summaries are displayed on the release listing (default: true)
$stalone_serveArticleBody = true; // if set to false, release links will point to prMac. If true, they will be served by this script.

$stalone_submittedTBs = null;
$_prmac_cacheExpire = 4*60*60;

if (!preg_match('/[\w\d]{6,15}/i', $stalone_agencyCode))
	exit("<h1>Invalid agency code.</h1><p>Please go to your prMac agency dashboard and retrieve this code.</p>");

if (!is_writable($_prmac_cacheDir) || !@file_exists("{$_prmac_cacheDir}/."))
	exit("<strong>Cache directory isn't writable or doesn't exist!</strong> Add write permissions to '{$_prmac_cacheDir}' (located at: '" . realpath($_prmac_cacheDir) . "').");

stalone_detectPrettyUrls();

/*if ((rand(1, $stalone_generateProbability) == 1) || (filesize($stalone_rssFilename) == 422))
	stalone_rewriteRSSFeed();
*/

$stalone_xml = isset($_GET['prmac_xml']);
